// Generated by scripts/optimize-images.mjs — do not edit by hand.
// Run `node scripts/optimize-images.mjs` to regenerate.

export const BLUR_DATA_URL: Readonly<Record<string, string>> = {
  "/images/home/authors/thumb.webp":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoMAAwAAoBCJQBOgNMUfKDAQ7m+gAD+9DvqhQI6y8KyEnKOGD6xeA1aU0Ae949daCcbnzHZbUV/71p+5VRMg7bbQu00mGh+hpw0fveD2Gw4x8j/xbYe9TKsSyS0AAAA",
  "/images/home/featured/cover.webp":
    "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAUAAoBCJYwCdADc9vMiAAD+/An94H+oWlKp1qjxHpRiXzXvEWW65TDlLc1yxGR6AAAA",
  "/images/home/hero/poster-1.webp":
    "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoMABAAAoBCJYwCdAYtBbTY7XXtYAD++lD5viLNfwNoSDZ/mEOvtEngr8ry97P7TTThDE+rhuFHMrGDL8A6nUyFofwGgfwrk4H0L4KOa/VvP4WAL71bAdZT8ehdNHgBSwQdgAAA",
  "/images/home/hero/poster-2.webp":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoMABAAAoBCJQBOgCBj45515tlFGgAA/tfx4erW7jTuR2zshja8kIa0odze3DeqY+fEY/A5qD97fTWghCcGS0L8i19XON5THv+LthfOOm6y3hUAn2a5MNhs5DJVAAAA",
  "/images/home/hero/poster-3.webp":
    "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwAgCdASoMABAAAoBCJYgCdAYv1bajQn4DwXsAAP74a8OWrM171uJ390F1c/kL0rZ9O6aHvrWaQdw528uewM/5kcdbGrEH9fM8pyYmee7ZYrBzkm8aceqsPP3xB6JsymzYNdqlTTmYSJonT1BR6c3TO2lAAAAA",
  "/images/home/interlude/main.webp":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAcAAoBCJaQAAscAngq4AAD+/An3h46xOLVZaZR6NwMX9a53+kszBrd8K9zGZLsdzy2Bdd+4NoAA",
  "/images/home/manifesto/bw.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoMAA8AAoBCJZwCdAELT8fr0xogAPkNFVeQE8Skp8bac+PTscUfYseeQz6WoOXkNE3HktL6XpqRAmHlps3xcCfL60ntl6BDbWEpv99FI/08qKG7dGwC1XjJYkKAAA==",
  "/images/home/moodboard/scattered-1.webp":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoMAAwAAoBCJYgCdAEX6r+XBXJKgAD5fXP+1TIupwJxgdTMhyaIyrge7aY9v8x1PRMFUZSoMk2uQasnLT8O2lnJvy52s4z8WmlEn5f/GGdCJe1vZ5oXwhx+lnb7tmAA",
  "/images/home/moodboard/scattered-2.webp":
    "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQAgCdASoMAAwAAoBCJQBOgCHhra5JEL8AAP11jjZqrL7AGalYjuqt8e7gndEpQWgFAlY1R/2SnvvBk+Wt5N7PW1tsAz83MDh9nG/FLNYwHXiUDyKsL+gV3nnqvpmgFBanj7mPFwx+HgHVcRJMkngAAAA=",
  "/images/home/moodboard/scattered-3.webp":
    "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoMAAwAAoBCJQBOgBuyfdTMknAA/kRLvqRcN2hvyOqbEd6C0QvGGWfz+MkosL5zVLHCVESU/Xo53h9kZpqruKFgiSpYl4WsaUZb8CcjoCGz3FuO1CMBnyu3j4ZTc/JwAAA=",
};
