#!/usr/bin/env node
// One-shot image pipeline: PNG → WebP + blur placeholders.
// Reqs: ffmpeg with libwebp on PATH (see ffmpeg -codecs | grep webp).
// Usage:  node scripts/optimize-images.mjs [--root public/images] [--force]
//
// Why ffmpeg (not sharp): no extra npm dependency, and our team's environment
// already has ffmpeg. If/when a CI image pipeline is wired up, swap to sharp.
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, extname, join, relative, sep } from "node:path";

const ROOT = process.cwd();
const args = process.argv.slice(2);
const rootArgIdx = args.indexOf("--root");
const SCAN_ROOT = join(ROOT, rootArgIdx >= 0 ? args[rootArgIdx + 1] : "public/images");
const FORCE = args.includes("--force");

const WEBP_QUALITY = "82";
const MAX_WIDTH = 1600; // hard cap; sources up to this width are kept native
const BLUR_WIDTH = 12;
const BLUR_QUALITY = "60";

const BLUR_MAP_PATH = join(SCAN_ROOT, "_blur-map.json");
const BLUR_TS_PATH = join(ROOT, "src/shared/lib/image-blur/blur-map.generated.ts");

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) yield* walk(full);
    else yield full;
  }
}

function ffmpeg(args) {
  execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", ...args], { stdio: "inherit" });
}

function toWebp(srcPng, dstWebp) {
  ffmpeg([
    "-i", srcPng,
    "-c:v", "libwebp",
    "-quality", WEBP_QUALITY,
    "-compression_level", "6",
    "-vf", `scale='min(${MAX_WIDTH},iw)':'-1'`,
    dstWebp,
  ]);
}

function makeBlurDataUrl(srcPng) {
  // Produce a tiny WebP via ffmpeg → base64-encode into a data URL.
  const tmpDir = mkdtempSync(join(tmpdir(), "blur-"));
  const tmpFile = join(tmpDir, "b.webp");
  try {
    ffmpeg([
      "-i", srcPng,
      "-c:v", "libwebp",
      "-quality", BLUR_QUALITY,
      "-compression_level", "6",
      "-vf", `scale=${BLUR_WIDTH}:-1`,
      tmpFile,
    ]);
    const buf = readFileSync(tmpFile);
    return `data:image/webp;base64,${buf.toString("base64")}`;
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

function publicPathFor(absPath) {
  // public/images/home/hero/x.png  →  /images/home/hero/x.png
  const rel = relative(join(ROOT, "public"), absPath).split(sep).join("/");
  return "/" + rel;
}

function main() {
  if (!existsSync(SCAN_ROOT)) {
    console.error(`Scan root not found: ${SCAN_ROOT}`);
    process.exit(2);
  }
  const existingBlurMap = existsSync(BLUR_MAP_PATH)
    ? JSON.parse(readFileSync(BLUR_MAP_PATH, "utf8"))
    : {};

  const pngs = [];
  for (const f of walk(SCAN_ROOT)) {
    if (extname(f).toLowerCase() === ".png") pngs.push(f);
  }
  pngs.sort();

  const blurMap = { ...existingBlurMap };
  let converted = 0;
  let skipped = 0;

  for (const png of pngs) {
    const webp = png.slice(0, -".png".length) + ".webp";
    const dir = dirname(webp);
    if (!existsSync(dir)) {
      console.error("Missing dir:", dir);
      process.exit(2);
    }

    const needConvert = FORCE || !existsSync(webp) || statSync(png).mtimeMs > statSync(webp).mtimeMs;
    if (needConvert) {
      process.stdout.write(`webp: ${relative(ROOT, png)} → ${relative(ROOT, webp)}\n`);
      toWebp(png, webp);
      converted++;
    } else {
      skipped++;
    }

    const publicPath = publicPathFor(webp);
    if (FORCE || !blurMap[publicPath]) {
      blurMap[publicPath] = makeBlurDataUrl(png);
    }
  }

  // Sort keys for stable diffs.
  const sorted = Object.fromEntries(Object.keys(blurMap).sort().map((k) => [k, blurMap[k]]));
  writeFileSync(BLUR_MAP_PATH, JSON.stringify(sorted, null, 2) + "\n", "utf8");

  // Mirror to TS so views can import without going through public/.
  const tsBody =
    "// Generated by scripts/optimize-images.mjs — do not edit by hand.\n" +
    "// Run `node scripts/optimize-images.mjs` to regenerate.\n\n" +
    "export const BLUR_DATA_URL: Readonly<Record<string, string>> = " +
    JSON.stringify(sorted, null, 2) +
    ";\n";
  if (!existsSync(dirname(BLUR_TS_PATH))) {
    console.error("Missing dir for TS blur map:", dirname(BLUR_TS_PATH));
    process.exit(2);
  }
  writeFileSync(BLUR_TS_PATH, tsBody, "utf8");

  console.log(`\nDone. converted=${converted}, skipped=${skipped}, total=${pngs.length}`);
  console.log(`Blur map: ${relative(ROOT, BLUR_MAP_PATH)} (${Object.keys(sorted).length} entries)`);
  console.log(`TS module: ${relative(ROOT, BLUR_TS_PATH)}`);
}

main();


